# Generated by Django 4.0.5 on 2022-06-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(verbose_name='Tempo de preparação'),
        ),
    ]
